[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
builders3_a1 = "RCh4rrijMZstrGNNgSKdNz3UTDQYJDHTKvFMRA5mEm7"

[programs.localnet]
builders3_a1 = "RCh4rrijMZstrGNNgSKdNz3UTDQYJDHTKvFMRA5mEm7"

[registry]
url = "https://github.com/coral-xyz/anchor"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
